# Testing duckDB and load file

## Test loding data into DuckDB

In [1]:
from cbb_predictor.db import get_connection

con = get_connection(read_only=True)
con.sql("SELECT GameType, COUNT(*) AS n FROM team_games GROUP BY GameType").df()

  GameType       n
0        R  249058
1        T    2898

## Exploring data in DuckDB

In [2]:
con.sql("SELECT AVG(Win) FROM team_games WHERE Loc = 'H'").df()

   avg(Win)
0  0.654833

In [3]:
con.sql("SELECT COUNT(DISTINCT TeamID) FROM team_games").df()

   count(DISTINCT TeamID)
0                     372

In [4]:
con.sql("SELECT Season, avg(Possessions) AS avg_possessions FROM team_games GROUP BY Season ORDER BY Season").df()

    Season  avg_possessions
0     2003        69.081947
1     2004        68.611308
2     2005        68.174992
3     2006        67.874004
4     2007        67.705008
5     2008        67.919163
6     2009        67.376428
7     2010        67.729052
8     2011        67.310891
9     2012        66.671617
10    2013        66.495503
11    2014        67.238359
12    2015        65.524733
13    2016        69.721583
14    2017        70.071837
15    2018        70.033215
16    2019        69.647455
17    2020        69.673501
18    2021        70.702614
19    2022        69.567757
20    2023        69.417759
21    2024        70.036696
22    2025        69.533048
23    2026        69.958436

In [5]:
con.sql("""
    SELECT t.TeamName, g.Season, AVG(g.Win) AS win_pct, COUNT(*) AS games, AVG(g.Score - g.OppScore) as avg_margin
    FROM team_games AS g
    JOIN teams AS t ON g.TeamID = t.TeamID
    GROUP BY t.TeamName, g.Season
    ORDER BY win_pct DESC, avg_margin DESC
    LIMIT 5
""").df()

     TeamName  Season   win_pct  games  avg_margin
0    Kentucky    2015  0.974359     39   20.051282
1  Wichita St    2014  0.971429     35   14.914286
2     Gonzaga    2021  0.968750     32   21.281250
3    Miami OH    2026  0.965517     29   10.862069
4     Memphis    2008  0.950000     40   17.975000

In [6]:
con.sql("""
    SELECT t.TeamName, g.Season, AVG(g.Win) AS win_pct, COUNT(*) AS games, AVG(g.Score - g.OppScore) as avg_margin
    FROM team_games AS g
    JOIN teams AS t ON g.TeamID = t.TeamID
    WHERE t.TeamName = 'Arkansas'
    GROUP BY t.TeamName, g.Season
    HAVING COUNT(*) >= 20
    ORDER BY win_pct DESC
    LIMIT 5
""").df()

   TeamName  Season   win_pct  games  avg_margin
0  Arkansas    2021  0.781250     32   10.625000
1  Arkansas    2026  0.764706     34    9.852941
2  Arkansas    2022  0.756757     37    7.648649
3  Arkansas    2015  0.750000     36    7.277778
4  Arkansas    2017  0.722222     36    5.444444

In [7]:
con.close()

### Key Takeaways

* Can do all things done with pandas in the Kaggle notebook using SQL
* The queries are a lot more streamlined here
* The SQL results match notebook 01’s pandas results
* This makes me believe the load script works as expected